### ISSUE TITLE
LittleFS Error: mklittlefs not found!

### ISSUE THREAD

**Issue by DiegoRodasS** [earlephilhower/arduino-esp8266littlefs-plugin#1]
Hello Earl,
I'm getting (LittleFS Error: mklittlefs not found!) when trying to upload files to the esp, there is already created the data directory and a .html file inside it.

**Comment by earlephilhower** [comment]
You need the mklittlefs tool  It should be installed by the IDE automatically, but if you are using GIT, then you need to run `python get.py` in the `tools` directory to download it.

**Comment by DiegoRodasS** [comment]
Excuse me,  I'm working on windows nt, I don't know what's GIT and don't know anything about python.

**Comment by DiegoRodasS** [comment]
I tried what you told me, but I got this :

$ PATH=$PATH:/c/Python27/
$ python get.py
C:\Python27\python.exe: can't open file 'get.py': [Errno 2] No such file or directory
So, do I have to install the core with git to solve the issue?

**Comment by earlephilhower** [comment]
The get.py script is in your IDE clone location in the `tools` directory.  It's not a python built-in, of course, so you need to be in that dir to make it work...

**Comment by DiegoRodasS** [comment]
As I didn't install the core using git... I'll reinstall the Core using the IDE, if it doesn't work, then the IDE and the Core, so on íf it doesn't, I'll clone the repositiry with GIT.

**Comment by earlephilhower** [comment]
Ah, that explains it!  2.5.2 did not have LittleFS support, it was only bugfixes for 2.5.0.  You need to use GIT installs if you want to try littleFS, or wait for 2.6.0...

**Comment by earlephilhower** [comment]
Closing as LittleFS has been in the core toolset for a long time now.
