### ISSUE TITLE
More verbose output

### ISSUE THREAD

**Issue by siteswapjuggler** [earlephilhower/arduino-esp8266littlefs-plugin#11]
Hello I'm interested into more verbose output so I can bash the upload to many OtA ESP. I tried to modify  the source but do not succeed to compile. Can you help me with this ?

**Comment by earlephilhower** [comment]
Sorry, I don't quite grok what you're trying to do.  You need a working java toolchain, and should be able to do a make (modify the paths accordingly in the Makefile) to add all the system.out.println()s you need.  Good luck!

**Comment by siteswapjuggler** [comment]
Sorry I should have close this earlier I found a solution in the afternoon. The paths has to be changed in the Makefile the compilation then work like a charm :)
