### ISSUE TITLE
Flash sketch or LittleFS first?

### ISSUE THREAD

**Issue by 877dev** [earlephilhower/arduino-esp8266littlefs-plugin#13]
As per the title I am assuming that the sketch should be flashed first, then the littleFS data uploaded second?

Does the flashing of the sketch create a partition on the ESP, or does the littleFS upload create its own partition?￼

When flashing littleFS for the second time, does it completely overwrite the partition, e.g. no old files remain?￼

I know it might seem obvious but I am not sure.￼

**Comment by earlephilhower** [comment]
Sketch then FS seems safe enough.  If you do the other way, there is a change the old sketch might format the FS when it powers up after the FS is uploaded (i.e. if it was expecting SPIFFS).
