### ISSUE TITLE
Upload deletes Wifi configuration (ESPAsyncWebServer, ESPAsyncWiFiManager & LittleFS)

### ISSUE THREAD

**Issue by rogerknop** [earlephilhower/arduino-esp8266littlefs-plugin#14]
Hi,
I am using ESPAsyncWebServer, ESPAsyncWiFiManager and LittleFS.
The WifiManager is creating a config.json file and for the Webserver I have created the data folder with html and css files.
The problem now is that as soon as I trigger the File Upload from the IDE, the configuration for the Wifi Connection is gone and I need reconfigure Wifi.
Is there a possibility to exclude files from the upload process?
Thanks, Roger

**Comment by earlephilhower** [comment]
Nope, not possible.  The tool builds a binary disk image blob that the core just copies over.

You can copy the config files from the 8266, then run mklittlefs and uplaod, if you need to preserve them.

OTW, you need to use a different method (like web uploading individual files or FTP or something).

Good luck!
