### ISSUE TITLE
LIttleFS plugin not working on big sur

### ISSUE THREAD

**Issue by Pius171** [earlephilhower/arduino-esp8266littlefs-plugin#16]
i followed the instructions in your github page but the littlefs option doesn't show up in arduino tools option

**Comment by earlephilhower** [comment]
The plugin is plain java and works on Big Sur, but needs to be in the right directory for the IDE to find and run it.

Please double check that you have expanded the zip into a `<ArduinoSketchDir>/tools/PicoLittleFS/tool/picolittlefs.jar` file.
````
$ ls -l ~/Arduino/tools/PicoLittleFS/tool/picolittlefs.jar 
-rw-r--r-- 1 earle earle 6715 Mar 30 23:00 /home/earle/Arduino/tools/PicoLittleFS/tool/picolittlefs.jar
````

**Comment by Pius171** [comment]
There is no picolittlefs directory in the expanded zip folder

**Comment by earlephilhower** [comment]
For the ESP8266 version, it will be a ESP8266LittleFS dir no extraction.  For the RPI Pico, it will be the Pico one.

**Comment by Pius171** [comment]
<img width="1440" alt="Screenshot 2021-04-24 at 21 25 37" src="https://user-images.githubusercontent.com/70412012/115972017-eba84f00-a543-11eb-8310-ec73d3ec1278.png">

<img width="1440" alt="Screenshot 2021-04-24 at 21 27 19" src="https://user-images.githubusercontent.com/70412012/115972033-ff53b580-a543-11eb-9dd4-933b91c0b390.png">

it still doesnt work. i am sorry i am disturbing you but i can't find any solution on the internet

**Comment by earlephilhower** [comment]
Looks like the right spot, but you're running the 2.0 beta.  Maybe it doesn't work with plugins?  Try 1.8.xxx if you can.
