### ISSUE TITLE
Not working with Arduino IDE 2.0

### ISSUE THREAD

**Issue by DirkFedermann** [earlephilhower/arduino-esp8266littlefs-plugin#23]
Just wanted to save some one a little time and say: this plugin is not working with the Arduino IDE 2.0.
You have to download and install the Arduino IDE 1.8.x to use this plugin

And don't forget to copy over your 'boards manager URLs'

**Comment by Ce345** [comment]
Metoo.
Can not find a doc about why the/ a library is now invalid. Arduino should have explained and communicated the change from ide 1 to 2 and warned about the changes during the install proces of ide 2; also the github can be used for that purpose. Githubbers spend a lot of freetime in their library and are a important part of the system that make Arduino succesfull among hobbyists and professionals.

**Comment by pisolofin** [comment]
I have the same issue on new installation

**Comment by earlephilhower** [comment]
This is an Arduino IDE issue.  See #21
