### ISSUE TITLE
LittleFS Menu does not show in Arduino IDE 2.0.3 / Win 10 Pro 22H2

### ISSUE THREAD

**Issue by HeinzRuetschi** [earlephilhower/arduino-esp8266littlefs-plugin#24]
Have installed the plugin according to the installation info: 
C:\Users\HR\Documents\Arduino\tools\ESP8266LittleFS\tool\esp8266littlefs.jar
However, the menu ESP8266 LittleFS Data Upload does not show up as indicated in the instruction screenshot.
Used the latest version in this repository.
Any help or solutions? Thank you.

**Comment by earlephilhower** [comment]
See https://github.com/earlephilhower/arduino-esp8266littlefs-plugin/issues/21 .  IDE 2.0 does not support plugins.
