### ISSUE TITLE
IDE 2.2.1 not supported?

### ISSUE THREAD

**Issue by shooshx** [earlephilhower/arduino-esp8266littlefs-plugin#28]
I'm trying this with the latest IDE version, 2.2.1 and the menu item doesn't appear
Can this plugin be updated please?

**Comment by laurensV** [comment]
Same problem here..

**Comment by earlephilhower** [comment]
## Arduino IDE 2.x users
Please see the [arduino-littlefs-plugin](https://github.com/earlephilhower/arduino-littlefs-upload) for use under IDE 2.2.1 or later
